### PR TITLE
adapt to netstandart2.0

### PR DESCRIPTION
**Pull request by hin-longkid**
1. make the project build with multi target.
2. refactor some code to adapt to netstandart2.0.

### CODE REVIEW

**Comment by donnytian** [comment]
Since we currently target on .net framework 4.5, shouldn't we target on netstandard1.1?
BTW, please fix appveyor compile error.

**Comment by donnytian** [comment]
As I mentioned, can you please help to target on netstandard1.1 instead of netstandard2.0?

**Comment by hin-longkid** [comment]
First off all, i try to target on netstandard1.1, casue that will be perfect. But i just find out two NPOI packages for netstandard version.
1. [Savorboard.NPOI.Core.Ooxml](https://www.nuget.org/packages/Savorboard.NPOI.Core.Ooxml/) for netstandard 1.6
2. [DotNetCore.NPOI](https://www.nuget.org/packages/DotNetCore.NPOI/) for netstandard 2.0
So, i choose the new one, and make the project build with multi target.

**Comment by donnytian** [comment]
What you found are .net core projects. 
NPOI is targeting .net framework but not .net core.
So I don't see any point here to follow those projects.

Actually this tool will never work with `#if DNXCORE50`, because NPOI itself is not available on that platform and this tool is built on NPOI. 

Another point is that since this is an utility tool, the lower version we support, the more users/ projects can use it. So we should keep as low as possible on framework version to let more people use it.

I don't see any necessity to support `netstandard `for now. I just realized it.

Thanks for your attention and please let me know if you have any question!

**Comment by hin-longkid** [comment]
oh :), i get your idea, thanks all.

**Pull request closed without merging**
